---
title: "NetworkOfAssociationRules"
author: "Jean-Francois Chartier"
date: "4 mars 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Read rules of interest
```{r}
rules.interest=readRDS("rules.interest.96.rds")
rules.interest.df=readRDS("rules.interest.96.df.rds")
rules.interest.df <- rapply(rules.interest.df, function(x) as.character(x), classes="factor", how="replace")

kmeanDocModel=readRDS("bestKmeanDocModelOnSVDSpace2019-01-16.rds")

topic.frequency=readRDS("frequency.of.dicho.topic.rds")
topic.frequency <- rapply(topic.frequency, function(x) as.character(x), classes="factor", how="replace")

map.cluster.color=c(setColorsPalette17(as.character(kmeanDocModel$cluster)))%>%cbind(names(.),.)%>%unique(.)


```

#prepare data
```{r}
#convert as proportion
topic.frequency$proportion=sapply(topic.frequency$frequency.topic, function(x){
  (x/sum(topic.frequency$frequency.topic))
})

```

#function for colors
```{r}
setColorsPalette17<-function(categories){
  n <- length(unique(categories))
  qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
  #by selectin id 2 and 5, we subset palette Dark2 and Pastel2
  col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors[c(2,4,5)], rownames(qual_col_pals[c(2,4,5),]))) %>% unique()
  col_vector=col_vector[1: n]
  uniqueCat=unique(categories)
  colorOfTopic=sapply(categories, function(x) col_vector[which(uniqueCat==x)])
  return(colorOfTopic)
}
```



#Plot selected rules
based on that script: https://github.com/datastorm-open/visNetwork/issues/6
```{r}
library(arules)
library(arulesViz)
library(visNetwork)
library(igraph)

ig <- plot(rules.interest, method="graph", control=list(type="items") )
ig_df <- get.data.frame(ig, what = "both")


#get node type
id.node.assoc=ifelse(ig_df$vertices$label == "",T, F)
id.node.cluster=ig_df$vertices$label %in% unique(kmeanDocModel$cluster)
id.node.topic= (id.node.assoc ==  id.node.cluster)

#node shape
myNodeShape = ifelse(id.node.assoc == T,"dot", "triangle")
myNodeShape[id.node.cluster]="square"

#node type as group
node.type.as.group=rep(NA, length(ig_df$vertices$label))
node.type.as.group[id.node.assoc]=rules.interest.df$rhs
node.type.as.group[id.node.cluster]=ig_df$vertices$label[id.node.cluster]

#set assoc node label to NA in order to simplify the graph
ig_df$vertices$label[id.node.assoc]=NA #rules.interest.df$lhs

#node size
myNodeSize=ig_df$vertices$support
myNodeSize[id.node.cluster]=kmeanDocModel$size/sum(kmeanDocModel$size)
myNodeSize=myNodeSize*100
# keep only topics present in the network
topic.frequency=sapply(topic.frequency$topic, function(x){
  x %in% ig_df$vertices$label[id.node.topic]
})%>%subset(topic.frequency, .)
#set node size of topics
myNodeSize[id.node.topic]=topic.frequency$proportion*100
#mySize[is.na(mySize)]=min(mySize, na.rm = T)

#node value
myNodeValue=myNodeSize

#node color. set only topic node colors
myNodeColor=NA
myNodeColor[id.node.topic]="black"
myNodeColor[id.node.assoc]=lapply(node.type.as.group[id.node.assoc], function(x){
  i=which(map.cluster.color[,1]==x)
  map.cluster.color[i,2]
})%>%unlist(.)
myNodeColor[id.node.cluster]=lapply(node.type.as.group[id.node.cluster], function(x){
  i=which(map.cluster.color[,1]==x)
  map.cluster.color[i,2]
})%>%unlist(.)


#node id
myNodeId=ig_df$vertices$name

myNodes=nodes = data.frame(id = myNodeId, title = ig_df$vertices$label, ig_df$vertices, shape=myNodeShape, group=node.type.as.group, size=myNodeSize, value=myNodeValue, color=myNodeColor, font.size =30) 

#Edges

myEdges=ig_df$edges
#edge value as prediction accuracy
myEdges$value=NA
i=myNodes$id[id.node.cluster]
selected.edge=(myEdges$to %in% i)
#myEdges$from[selected.edge]
myEdges$value[selected.edge]=rules.interest.df$fMesure

#set id name for plot
myNodeIdForPlot=ig_df$vertices$label
myNodeIdForPlot[id.node.cluster]=paste0("cluster ", ig_df$vertices$label[id.node.cluster])
myNodeIdForPlot[id.node.assoc]=paste0("rule: ", rules.interest.df$lhs)
myNodes$node.id=myNodeIdForPlot
#change node.id
#myNodes$id=myNodeIdForPlot

#with options for selecting nodes
#network.visualizer=visNetwork(nodes = myNodes, edges = myEdges, width = "100%", height = "100%") %>% visEdges( arrows = "to" ) %>% visGroups() %>% visEdges(color=list("inherit"="to")) %>% visOptions( highlightNearest = T, nodesIdSelection = TRUE, selectedBy = list(variable="group"))%>%visPhysics(stabilization = FALSE)%>%visInteraction(navigationButtons = TRUE) 

network.visualizer=visNetwork(nodes = myNodes, edges = myEdges, width = "100%", height = "100vh") %>% visEdges( arrows = "to" ) %>% visGroups() %>% visEdges(color=list("inherit"="to")) %>% visOptions( highlightNearest = T, nodesIdSelection = F)%>%visPhysics(stabilization = FALSE)%>%visInteraction(navigationButtons = TRUE) 


saveRDS(network.visualizer, "network.visualizer.rds")
visSave(network.visualizer, file = "network.of.associative.rules.html")
```

#Create shiny app
```{r}
require(shiny)

ui <- fluidPage(theme = shinytheme("paper"), inverse=F, windowTitle= "PhiloSci topic network", title = "PhiloSci topic network", 
  fluidRow(
    column(
      width = 2,
      selectInput(inputId = "id.node", 
                  label = "Id node", 
                  choices = c("all"), 
                  selected = "all",
                  multiple = T),
      selectInput(inputId = "cluster",
                  label="Clusters of articles",
                  choices = c("all"), 
                  selected = "all",
                  multiple = T),
      selectInput(inputId = "id.rule",
                  label="Associative rules",
                  choices = c("all"), 
                  selected = "all",
                  multiple = T),
      selectInput(inputId = "node.size",
                  label="Node sizes",
                  choices = c("support", "confidence", "chi2", "count"), 
                  selected = "count",
                  multiple = F)
    ),
    column(
      width = 10,
      visNetworkOutput(outputId = "network", width = "100%", height = "100%")
    )
  )
)





server <- function(input, output) {
  output$network <- renderVisNetwork({
    network.visualizer
  })
  
  #observe({
    #visNetworkProxy("network") %>% visNodes(id = input$id.node)
  #})
}

shinyApp(ui = ui, server = server)
```

