---
title: "WordsToTopicsAnalysis"
author: "Jean-Francois Chartier"
date: "1 avril 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#read matrix Pr(word|topic)
```{r}
matrixTopicWord=data.table::fread("matrixTopicWord.csv", header=T, sep = ",", encoding = "UTF-8", stringsAsFactors = F, drop = 1)

#read topic names and category labels
matrixTopicLabels = data.table::fread("label_topics_by_christophe_180227_180611.csv", header=T, sep = ",", encoding = "UTF-8")

topicLabels=matrixTopicLabels$Topic[matrixTopicLabels$retained=="yes"]

#categories=matrixTopicLabels$Category[matrixTopicLabels$retained=="yes"]


matrixTopicWord=matrixTopicWord[matrixTopicLabels$retained=="yes",]
matrixTopicWord$topic.label=topicLabels
rownames(matrixTopicWord)=topicLabels

```


```{r}
library(ggplot2)
library(dplyr)
library(magrittr)
library(tidytext)
library(reshape2)

#ap_topics <- tidytext::tidy(ap_lda, matrix = "beta")


matrixTopicWord.long=reshape2::melt(matrixTopicWord[14:25], id.vars = c("topic.label"), variable.name = "word", value.name = "word.value")

ap_top_terms <- matrixTopicWord.long %>%
  group_by(topic.label) %>%
  top_n(10, word.value) %>%
  ungroup() %>%
  arrange(topic.label, -word.value)

#in aes: fill = factor(topic.label)
ap_top_terms %>%
  mutate(word = reorder(word, word.value)) %>%
  ggplot(aes(word, word.value)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic.label, scales = "free", ncol=3) +
  coord_flip()+
  #geom_text(color = "black",  size=1, hjust=0, vjust=0)+
  ggtitle("Top-10 words of topics")+
  theme_light(base_size = 8)+
  theme(axis.text=element_text(size=8, colour = "black"),
        axis.title=element_text(size=8, colour = "black"),
        title=element_text(size=8, colour = "black"))

```

